### ISSUE TITLE
Error when  unflatten()ing an empty Map

### ISSUE THREAD

**Issue by SteveLauC** [Cybersecurity-LINKS/json-unflattening#1]
### To reproduce

```toml
json-unflattening = "0.1.3"
serde_json = "1.0.117"
```

```rs
use json_unflattening::unflattening::unflatten;
use serde_json::Map;

fn main() {
    let empty_object = Map::new();
    let try_unflatten = unflatten(&empty_object);

    assert!(try_unflatten.is_err());
}
```

### Expected behavior

I am expecting `try_unflatten` will be an empty map as well since there is nothing in the original map.
